package mineSweeper.jogo;

import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import mineSweeper.udp.ClienteUdp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author laser
 */
public class ListarServidores extends javax.swing.JFrame {

    private List<ServerInfo> serverInfoList;
    private ServerInfo selectedServer;
    private ClienteUdp clienteUdp;
    private Thread threadClientUdp;

    //Essas duas variáveis foram criadas para receber o conteúdo do servidor udp (que é uma string e nesse momento é apenas o ip do servidor),
    //depois é possível passar mais informações pela string e criar esse objeto serverInfo para cada servidor
    private String selectedServerString;

    /**
     * Creates new form ListarServidores
     */
    public ListarServidores() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servCbx = new javax.swing.JComboBox<ServerInfo>();
        procurarBtn = new javax.swing.JButton();
        nomeLbl = new javax.swing.JLabel();
        nomeServLbl = new javax.swing.JLabel();
        dificuldadeLbl = new javax.swing.JLabel();
        dificuldadeServLbl = new javax.swing.JLabel();
        numeroSrvLbl = new javax.swing.JLabel();
        numeroServLbl = new javax.swing.JLabel();
        selecionarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        servCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servCbxActionPerformed(evt);
            }
        });

        procurarBtn.setText("Procurar");
        procurarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarBtnActionPerformed(evt);
            }
        });

        nomeLbl.setText("Nome:");

        nomeServLbl.setText("******");

        dificuldadeLbl.setText("Dificuldade:");

        dificuldadeServLbl.setText("******");

        numeroSrvLbl.setText("Nº Jogadores");

        numeroServLbl.setText("******");

        selecionarBtn.setText("Selecionar");
        selecionarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dificuldadeLbl)
                            .addComponent(numeroSrvLbl)
                            .addComponent(nomeLbl))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeServLbl)
                            .addComponent(numeroServLbl)
                            .addComponent(dificuldadeServLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(servCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionarBtn)
                            .addComponent(procurarBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procurarBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl)
                    .addComponent(nomeServLbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dificuldadeLbl)
                    .addComponent(dificuldadeServLbl))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroSrvLbl)
                    .addComponent(numeroServLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecionarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Faz o fetch da lista de servidores e atualiza a JComboBox
     *
     * @param evt
     */
    private void procurarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarBtnActionPerformed
        clienteUdp = new ClienteUdp(this);
        threadClientUdp = new Thread(clienteUdp);
        threadClientUdp.start();
    }//GEN-LAST:event_procurarBtnActionPerformed


    private void servCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servCbxActionPerformed
        selectedServer = (ServerInfo) servCbx.getSelectedItem();
        if (selectedServer != null) {
            updateLabels();
        }
    }//GEN-LAST:event_servCbxActionPerformed

    private void selecionarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarBtnMouseClicked
        //No caso de cliente o ip do servidor escolhido é passado 
        selectedServerString = ((ServerInfo) servCbx.getSelectedItem()).getIpAddressString();
        try {
            new MineFrame(false, selectedServerString);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(ListarServidores.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_selecionarBtnMouseClicked

    private void updateLabels() {
//        nomeServLbl.setText(selectedServer.getName());
//        dificuldadeServLbl.setText(selectedServer.getDifficulty());
//        numeroServLbl.setText(selectedServer.getNumberOfPlayers().toString());
    }

    public void updateServCbx(List<ServerInfo> lsi) {
        servCbx.removeAllItems();
        System.out.println("Logging inside condition, removed all items, adding new ones");
        lsi.forEach(servCbx::addItem);
        servCbx.setSelectedIndex(0);
    }

    public static void main(String[] args) {
        ListarServidores window = new ListarServidores();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dificuldadeLbl;
    private javax.swing.JLabel dificuldadeServLbl;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JLabel nomeServLbl;
    private javax.swing.JLabel numeroServLbl;
    private javax.swing.JLabel numeroSrvLbl;
    private javax.swing.JButton procurarBtn;
    private javax.swing.JButton selecionarBtn;
    private javax.swing.JComboBox servCbx;
    // End of variables declaration//GEN-END:variables
}
